### ISSUE TITLE
1. Feature: User can search their zipcode

### ISSUE THREAD

**Issue by Gallegos22** [Gallegos22/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Use your index.HTML file to create a website that matches the figma createed earlier on.
- [x] Create a heading within the `<body>` tag using using the `<h1>` element.
- [x] Create an icon on the top right corner of the heading to act as a navbar with no functionality for now.
- [x] Create a box in the center that says "zipcode" as placeholder text.
- [x] Right next to that box create a button that says "search" with no functionality for now
- [x] Make the page look pretty
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
