### ISSUE TITLE
2. Feature: User can add and view "Favorite Sunsets"

### ISSUE THREAD

**Issue by Gallegos22** [Gallegos22/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create a new header using the `<h2>` element
- [x]  Create a new button using the `<button>` element so the user can look up more sunsets
- [x]  Create a `<div>` to show when no sunsets have been added to Favorites
- [x]  Create dummy text inside a `<ul>` element to simulate how the entries will look once they have the information
- [x] Create an add button using the `<button>` element so user can add the sunset to their Favorites
- [ ] Create a function named `renderEntry` that creates a new `<ul>` that can later be saved into localStorage
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
